name: Create Release and Update Changelog

on:
  push:
    tags:
      - '*'

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Get the tag name
        id: get_tag_name
        run: echo "::set-output name=tag::$(echo ${GITHUB_REF#refs/tags/})"

      - name: Get previous tag
        id: get_previous_tag
        run: echo "::set-output name=previous_tag::$(git describe --tags --abbrev=0 ${GITHUB_SHA}^1)"

      - name: Get release notes
        id: get_release_notes
        run: |
          echo "::set-output name=notes::$(git log --pretty=format:'- %s' $(git describe --tags --abbrev=0 ${GITHUB_SHA}^1)..${GITHUB_SHA})"

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_tag_name.outputs.tag }}
          release_name: ${{ steps.get_tag_name.outputs.tag }}
          body: ${{ steps.get_release_notes.outputs.notes }}
          draft: false
          prerelease: false

      - name: Update CHANGELOG.md
        run: |
          echo "## ${{ steps.get_tag_name.outputs.tag }} - $(date +'%B %d, %Y')" > new_changelog.md
          echo "${{ steps.get_release_notes.outputs.notes }}" >> new_changelog.md
          echo "" >> new_changelog.md
          cat CHANGELOG.md >> new_changelog.md
          mv new_changelog.md CHANGELOG.md

      - name: Commit and push changes
        run: |
          git add CHANGELOG.md
          git commit -m "Update CHANGELOG.md for ${{ steps.get_tag_name.outputs.tag }}"
          git push
